//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "cdk")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub cdk_type: Option<i32>,
    pub code: Option<String>,
    pub use_status: Option<bool>,
    pub use_user: Option<i64>,
    pub use_time: Option<DateTime>,
    pub create_time: Option<DateTime>,
    pub update_time: Option<DateTime>,
    pub ext_data: Option<String>,
    pub desc: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
