//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use sea_orm::FromQueryResult;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "live_prize_history")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub live_id: Option<i64>,
    pub pool_id: Option<i64>,
    pub user_id: Option<i64>,
    pub action: Option<i64>,
    pub prize_ids: Option<String>,
    pub prize_items: Option<String>,
    pub create_time: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}


#[derive(FromQueryResult,Serialize, Deserialize)]
pub struct TopDraw {
    pub action: Option<i64>,
    pub user_id: Option<i64>,
    pub user_name: Option<String>,
}

#[derive(Clone, FromQueryResult,Serialize, Deserialize)]
pub struct DrawHistory {
    pub action: Option<i64>,
    pub user_id: Option<i64>,
    pub user_name: Option<String>,
    pub prize_ids: Option<String>,
    pub prize_items: Option<String>,
    pub create_time: Option<DateTime>,
}