//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::resource::Entity as Resource;
pub use super::role::Entity as Role;
pub use super::role_resource::Entity as RoleResource;
pub use super::user::Entity as User;
pub use super::user_role::Entity as UserRole;

