//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "prize_pool")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub pool_name: Option<String>,
    pub pool_type: Option<i32>,
    pub share_pool: Option<bool>,
    pub strategy: Option<i32>,
    pub status: Option<bool>,
    pub create_time: Option<String>,
    pub update_time: Option<String>,
    pub pool_desc: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
