[package]
name = "model"
version = "0.1.0"
edition = "2021"

[lib]
name = "model"
path = "src/lib.rs"


[dependencies]
serde = { version = "1.0.203", features = ["derive"] }
common = { path = "../common" }