pub mod user_service;
pub mod auth_service;
pub mod role_service;
pub mod resource_service;
pub mod email_service;
pub mod prize_pool_service;
pub mod prize_pool_item_service;
pub mod live_prize_pool_service;
pub mod live_prize_pool_item_service;
pub mod draw_history_service;
pub mod cdk_service;
mod manager;